/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CallHistoryRouteImport } from './routes/call-history'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as LiveCallsRouteImport } from './routes/live-calls'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PhoneSystemRouteImport } from './routes/phone-system'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryRoute = CallHistoryRouteImport.update({
  id: '/call-history',
  path: '/call-history',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveCallsRoute = LiveCallsRouteImport.update({
  id: '/live-calls',
  path: '/live-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneSystemRoute = PhoneSystemRouteImport.update({
  id: '/phone-system',
  path: '/phone-system',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/admin/system-health',
  path: '/admin/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/call-history': typeof CallHistoryRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/live-calls': typeof LiveCallsRoute
  '/login': typeof LoginRoute
  '/phone-system': typeof PhoneSystemRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sms': typeof SmsRoute
  '/support': typeof SupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/call-history': typeof CallHistoryRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/live-calls': typeof LiveCallsRoute
  '/login': typeof LoginRoute
  '/phone-system': typeof PhoneSystemRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sms': typeof SmsRoute
  '/support': typeof SupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/call-history': typeof CallHistoryRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/live-calls': typeof LiveCallsRoute
  '/login': typeof LoginRoute
  '/phone-system': typeof PhoneSystemRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sms': typeof SmsRoute
  '/support': typeof SupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/call-history'
    | '/campaigns'
    | '/contacts'
    | '/live-calls'
    | '/login'
    | '/phone-system'
    | '/recordings'
    | '/settings'
    | '/signup'
    | '/sms'
    | '/support'
    | '/admin/login'
    | '/admin/revenue'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/call-history'
    | '/campaigns'
    | '/contacts'
    | '/live-calls'
    | '/login'
    | '/phone-system'
    | '/recordings'
    | '/settings'
    | '/signup'
    | '/sms'
    | '/support'
    | '/admin/login'
    | '/admin/revenue'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/call-history'
    | '/campaigns'
    | '/contacts'
    | '/live-calls'
    | '/login'
    | '/phone-system'
    | '/recordings'
    | '/settings'
    | '/signup'
    | '/sms'
    | '/support'
    | '/admin/login'
    | '/admin/revenue'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  CallHistoryRoute: typeof CallHistoryRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactsRoute: typeof ContactsRoute
  LiveCallsRoute: typeof LiveCallsRoute
  LoginRoute: typeof LoginRoute
  PhoneSystemRoute: typeof PhoneSystemRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SmsRoute: typeof SmsRoute
  SupportRoute: typeof SupportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-history': {
      id: '/call-history'
      path: '/call-history'
      fullPath: '/call-history'
      preLoaderRoute: typeof CallHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-calls': {
      id: '/live-calls'
      path: '/live-calls'
      fullPath: '/live-calls'
      preLoaderRoute: typeof LiveCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-system': {
      id: '/phone-system'
      path: '/phone-system'
      fullPath: '/phone-system'
      preLoaderRoute: typeof PhoneSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/admin/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  CallHistoryRoute: CallHistoryRoute,
  CampaignsRoute: CampaignsRoute,
  ContactsRoute: ContactsRoute,
  LiveCallsRoute: LiveCallsRoute,
  LoginRoute: LoginRoute,
  PhoneSystemRoute: PhoneSystemRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SmsRoute: SmsRoute,
  SupportRoute: SupportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
